### ISSUE TITLE
Define the IPVM roadmap 

### ISSUE THREAD

**Issue by bdehaynin** [RhizomeDB/rs-rhizome#36]
**Preliminary questions:** 
- What are our objectives for the next 6 months? 
- Will the team working on IPVM evolve over the next 6 months?
- What dependencies does IPVM have? 
   - UCAN
   - go-car mirror
   - WASM
   - FVM?
   - WNFS server refactor?  

**What topics still need to be investigated before being able to go into production? 
This is a non exhaustive list, feel free to add new entries and order them by priority (a checked box means it needs to be investigated):**
- [ ] Cost semantics
- [ ] Trust & Verification Model
- [ ] Effect Systems
- [ ] Cooperative Optimization
- [ ] Declarative Invocation
- [ ] Captured Session / Receipts
- [ ] Scheduler
- [ ] Trust Model
- [ ] Payments
- [ ] Managed Effects

**(From the [spec page](https://github.com/ipvm-wg/spec#trust--verification-model)) What is the priority order of these IPVM high-level attributes?** (checked box for reorder)
- [ ] Wasm-on-IPFS
- [ ] Declarative invocation
- [ ] Captured results, re-ingested to IPFS
- [ ] A distributed scheduler
- [ ] Single vs cron, local vs remote vs either, etc
- [ ] Matchmaking
- [ ] Poster/acceptor
- [ ] Push-to-remote
- [ ] (Global) memoization table & adaptive optimization
- [ ] Managed effects (via an IPVM runtime)
- [ ] Mobile (ambient) computing, compute-to-data, and data-to-compute
- [ ] "The HTTP of Compute"
- [ ] Stretch: autonomous agents 

**(From the [Figma](https://www.figma.com/file/Tsdcncvv2mh9uPXqcWOnFB/IPVM-Dependencies-%26-Roadmap?node-id=0%3A1&t=QzB9pDjqE9Jn1aLF-0)), what is the order of priority for these items? Are there duplicates with the list above?** (checked box for reorder)
- [ ] Wasm execution MVP (duplicate?)
- [ ] Permissions
- [ ] Common Effects (duplicate?)
- [ ] Determinisitic Portable execution
- [ ] Jobs
- [ ] Data
- [ ] Scheduler (duplicate)

**What are the different phases of the roadmap and their objectives?** 
1. Research/Learning phase 
   - Find out what our use cases are and how to solve them in the most efficient way as well as what we'll need to do so. 
2. Design/specs definition
3. Development 
   - Create a first draft of the service to see if it functionnally works 
4. Testing 
5. Polishing
6. Deployment

**From the [spec page](https://github.com/ipvm-wg/spec#trust--verification-model), is this up to date?**
A. Learning Phase
1. Bash-script store/load/run Wasm from IPFS
2. Memoization table
3. Local
    - Remote, incl demo "look how fast it is on a remote machine now"
    - Bash-script module pipelining, capturing intermediate results
9. Experimentation with ABI (C conventions?)
10. Pure effects (e.g. atomic FS or DB read/write)
11. Initial attempt to run adaptive optimization on common partial applications

B. Specs
- IPLI & session receipts
- Scheduler & matchmaking
- Memoized result format & lookup
- Capability model
- Offline (SPKI)
- Online (ocap/CapTP)
- Verification mechanisms
- Compute on encrypted data (trusted & FHE)
